import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import {ThemeProvider} from "@/context/ThemeProvider";
import {BGGrid} from "@/components/BGGrid";
import {SignerProvider} from "@/context/SignerProvider";
import {Card, CardContent} from "@/components/ui/card";
import Navigation from "@/components/shared/Navigation";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <SignerProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <main className="mx-auto container max-w-[calc(65ch+100px)]  min-h-screen flex flex-col py-4 md:py-8 px-2 md:px-4">
              <Card className="">
                <Navigation />
                <CardContent>
                  <BGGrid>{children}</BGGrid>
                </CardContent>
              </Card>
            </main>
          </ThemeProvider>
        </SignerProvider>
      </body>
    </html>
  );
}
